/// <reference lib="deno.ns" />
import { copy, emptyDir, exists } from '@std/fs';
import { load } from '@std/dotenv';

// the OpenBao address comes from BAO_ADDR (environment or .env), so it stays out of the repo.
// deno bundle has no --define, so it's written to src/config.gen.ts and bundled like any module
await load({ export: true });
const baoAddr = Deno.env.get('BAO_ADDR');
if (!baoAddr) {
  console.error('BAO_ADDR is not set; using https://openbao.example.net');
}
const baoAddress = new URL(baoAddr || 'https://openbao.example.net').origin;

await Deno.writeTextFile(
  'src/config.gen.ts',
  `// generated by scripts/build.ts from BAO_ADDR; do not edit or commit\n` +
    `export const BAO_ADDR = ${JSON.stringify(baoAddress)};\n`
);

await emptyDir('dist');

const bundle = await new Deno.Command(Deno.execPath(), {
  args: [
    'bundle',
    '--platform=browser',
    '--format=esm',
    '--outdir=dist',
    // --minify also makes deno bundle pick the production builds of React
    ...(Deno.env.get('NODE_ENV') === 'production' ? ['--minify'] : []),
    'src/sidepanel.tsx',
    'src/background.ts'
  ],
  stdout: 'inherit',
  stderr: 'inherit'
}).output();
if (!bundle.success) {
  Deno.exit(bundle.code);
}

const manifest = JSON.parse(await Deno.readTextFile('manifest.json'));
manifest.host_permissions = [`${baoAddress}/*`];
await Deno.writeTextFile('dist/manifest.json', JSON.stringify(manifest, null, 2) + '\n');
await Deno.copyFile('static/sidepanel.html', 'dist/sidepanel.html');
if (await exists('images')) {
  await copy('images', 'dist/images');
}
